package:
  name: sql-agent-tool
  version: "0.1.5"

source:
  url: https://files.pythonhosted.org/packages/22/de/f1fac2c8a2d14270831eb205efb157925914fa4efa166a7a7d78f59add89/sql_agent_tool-0.1.5.tar.gz
  sha256: 29563034EA7A5E8F7BE0966C57E4E4D612CBAE99EA11A00572DA60B8F43D3D15

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.10
    - pip
  run:
    - python >=3.10
    - sqlalchemy >=2.0
    - psycopg2-binary >=2.9
    - pydantic >=2.0
    - sqlparse >=0.4
    - openai ==1.72.0
    - google-google-generativeai ==0.8.4
    - python-dotenv >=0.20
    - groq >=0.1

test:
  imports:
    - sql_agent_tool
    - psycopg2
  commands:
    - python -c "import psycopg2; print('psycopg2 version:', psycopg2.__version__)"
    - python -c "import sql_agent_tool"
  requires:
    - pip

about:
  home: https://github.com/Dadiya-Harsh/sql-tool
  license: MIT
  license_file: LICENSE
  summary: A secure SQL tool for AI agents to interact with databases
  description: |
    A Python package to securely access and query SQL databases with natural language,
    designed for use in AI agent frameworks.
  dev_url: https://github.com/Dadiya-Harsh/sql-tool
  doc_url: https://github.com/Dadiya-Harsh/sql-tool/blob/main/README.md

extra:
  recipe-maintainers:
    - Dadiya-Harsh
