{% set name = "sql-agent-tool" %}
{% set version = "0.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sql_agent_tool-{{ version }}.tar.gz
  sha256: b3f56e9f9f4ab31e1ebdabe02021258da43748c4c2d1e8551b13c96b691463c7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools >=61.0
    - pip
  run:
    - python >=3.10
    - pip
    - sqlalchemy
    - sqlparse
    - pydantic
    - groq
    - openai
    - psycopg2
    - google-generativeai
    - psycopg2-binary
    - python-dotenv

test:
  imports:
    - sql_agent_tool
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Dadiya-Harsh/sql-tool
  summary: A secure SQL tool for AI agents to interact with databases
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Dadiya-Harsh-wappnet
